name: Comment
run-name: GitHub API Comment Sample

on: pull_request

jobs:
  comment:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Post a PR Comment
        run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
# P56 Code 3.20
