name: JSON functions

on: push

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "JSON - ${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }} # githubコンテキストをJSON文字列でダンプ
# P49 COde 3.10
