name: Hash functions

on: push

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: echo "HASH - ${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml')}} # ハッシュ値生成
# P50 Code 3.12
