name: Intermediate environment variables

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # コンテキストの値を環境変数に代入
    steps:
      - run: echo "${ACTOR}" # envコンテキストを参照
# P40 Code 3.4
