name: Override environment variables

on: push

env:
  EXAMPLE: Defined by workflow level

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo Workflow level - "{ EXAMPLE }"
      - env:
          EXAMPLE: Defined by step level
        run: echo Overrode level - "{ EXAMPLE }"
# P39 Code 3.3
