# 静的解析ツール `actionling` を使用して
# ディレクトリ内の `yaml` ファイル変更時に静的解析を行う
# Author: mendelssonnusaic
name: Static analysis
run-name: Static analysis workflow sample

on:
  pull_request:
    paths: [".github/workflows/*.yml", ".github/workflows/*.yaml"]

defaults: # デフォルトシェル
  run:
    shell: bash

concurrency: # 自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5 # タイムアウト
    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: "false"

      - name: Execute actionlint container
        run: | # 静的解析の実行
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:v1.6.24

# P77 Code 4.6
